version: "3.5"
services:
  rstudio:
    environment:
      - USER=admin
      - PASSWORD=admin
    image: "rocker/tidyverse:latest"
    volumes:
     #- /tmp/R_and_Jupyter_scripts:/home/admin/R_and_Jupyter_scripts
      - ./R_and_Jupyter_scripts:/home/admin/R_and_Jupyter_scripts
    container_name: rstudio
    ports:
      - 8787:8787

  jupyter:
    image: 'jupyter/datascience-notebook:latest'
    environment:
      - JUPYTER_TOKEN=admin
    ports:
      - 8888:8888
    volumes:
     #- /tmp/R_and_Jupyter_scripts:/home/admin/R_and_Jupyter_scripts
      - ./R_and_Jupyter_scripts:/home/admin/R_and_Jupyter_scripts
    working_dir: /home/admin/R_and_Jupyter_scripts
    container_name: jupyter
